# TMUX CONFIG FILE by patrickhausser

bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# set -g default-shell /bin/fish

if-shell 'infocmp -x tmux-256color >/dev/null 2>&1' \
    'set -g default-terminal "tmux-256color"' \
    'set -g default-terminal "screen-256color"'
set -g status-interval 2
set -g renumber-windows on

set -g base-index 1
setw -g pane-base-index 1

set -g status-right "#(date +%H:%M) "
set -g status-left ""
setw -g window-status-format " #I:#W#F "
setw -g window-status-current-format " #I:#W#F "
set -g status-style fg=black,bg=white
set -g window-status-current-style fg=white,bg=black
set -g message-style fg=black,bg=white
set -g pane-active-border-style fg=grey,bg=grey
set -g pane-border-style fg=grey

if-shell '[ -f ~/.tmux.conf.local ]' 'source-file ~/.tmux.conf.local'
